-- LinguAI Bridge
-- Step 1: Create the vocabulary table in Supabase/PostgreSQL.
--
-- How to use:
-- 1. Open Supabase Dashboard.
-- 2. Go to SQL Editor.
-- 3. Paste and run this script.

CREATE TABLE IF NOT EXISTS public.vocabulary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    word TEXT NOT NULL UNIQUE,
    grammar JSONB NOT NULL,
    word_formation JSONB NOT NULL,
    definition TEXT NOT NULL,
    synonyms TEXT[] NOT NULL DEFAULT '{}',
    ielts_level TEXT NOT NULL,
    category TEXT NOT NULL,
    status TEXT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_reviewed TIMESTAMPTZ
);

-- Helpful indexes for future search/filter features in the Next.js frontend.
CREATE INDEX IF NOT EXISTS idx_vocabulary_category
    ON public.vocabulary (category);

CREATE INDEX IF NOT EXISTS idx_vocabulary_status
    ON public.vocabulary (status);

CREATE INDEX IF NOT EXISTS idx_vocabulary_ielts_level
    ON public.vocabulary (ielts_level);

CREATE INDEX IF NOT EXISTS idx_vocabulary_synonyms
    ON public.vocabulary USING GIN (synonyms);
